version: "3.9"
services:
  app:
    build: .
    image: sapi
    container_name: sapi_app
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    ports:
      - "6028:6028"
    volumes:
      - .:/app
  apptest:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: sapi
    container_name: sapi_app
    environment:
      POSTGRES_USER: "${TEST_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${TEST_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${TEST_POSTGRES_DB}"
      POSTGRES_PORT: "${TEST_POSTGRES_PORT}"
    ports:
      - "6028:6028"
    volumes:
      - .:/app
  postgres:
    image: postgres
    container_name: sapi_db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"
  postgres_test:
    extends: postgres
    container_name: sapi_db_test
    environment:
      POSTGRES_USER: "${TEST_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${TEST_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${TEST_POSTGRES_DB}"
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
  migrate:
    image: migrate/migrate
    volumes:
        - ./db/migrations:/migrations
    command: [
      "-path", 
      "/migrations", 
      "-database", 
      "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", 
      "up", "3"]
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
