FROM golang:1.18.2

RUN apt-get update

WORKDIR /testdir

COPY . .

RUN go mod download \ 
&& go get github.com/dimeko/sapi/api \
&& go get github.com/dimeko/sapi/store 

CMD ["go", "test", "-v", "github.com/dimeko/sapi/store/rdbms", "github.com/dimeko/sapi/api"]
